- hosts: localhost
  gather_facts: yes
  vars:
    target_aws_region: us-west-2
  vars_files:
    - secret.yml
  tasks:
    - include: infra_tasks/infrastructure.yaml
    - include: infra_tasks/security_group.yaml
    - include: infra_tasks/ec2.yaml
    - include: infra_tasks/checkpoint.yaml

- name: web app setup
  hosts: win
  gather_facts: no
  vars_files: [ "secret.yml" ]
  tasks:
    - include: app_tasks/app.yaml
  